// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANxebcMvhxjNGAbF6kEJK9J9fxSVGiDr0',
    appId: '1:513540790841:android:afe82907ed7db52bf8cbe8',
    messagingSenderId: '513540790841',
    projectId: 'lingola-stories-kids',
    storageBucket: 'lingola-stories-kids.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg9tnGXoFyZsmonFJBEPnaphx4mEw_hJc',
    appId: '1:513540790841:ios:f549f5711e6a8358f8cbe8',
    messagingSenderId: '513540790841',
    projectId: 'lingola-stories-kids',
    storageBucket: 'lingola-stories-kids.firebasestorage.app',
    androidClientId: '513540790841-73pf8ektsgjun9lgb5010fepth26kebs.apps.googleusercontent.com',
    iosClientId: '513540790841-6cp5skhbd31chbcqpbph7gnghljtqspi.apps.googleusercontent.com',
    iosBundleId: 'com.flywork.lingolastorieskidsapp',
  );

}